- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{lookup('env', 'USER')}}"
    groups:
      - docker
    append: yes

- name: Check for cuda
  ansible.builtin.shell: command -v nvcc
  register: cuda_exists
  ignore_errors: yes

- name: Install nvidia-docker2
  become: true
  when: cuda_exists is not failed
  register: nvidia_docker_installed
  ansible.builtin.apt:
    name: nvidia-docker2
    state: latest

- name: Restart docker
  become: true
  when: nvidia_docker_installed is changed
  ansible.builtin.service:
    name: docker
    state: restarted

